# Generated by Django 3.1.7 on 2021-03-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210305_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('PS', 'Person'), ('CA', 'Cat')], default='PS', max_length=2)),
                ('is_real', models.BooleanField()),
                ('photo_url', models.ImageField(unique=True, upload_to='images')),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
